apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-affinity
  namespace: telecom

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis

            topologyKey: kubernetes.io/hostname

      containers:
      - name: nginx
        image: nginx:latest
