apiVersion: batch/v1
kind: CronJob

metadata:
  name: hello-cron
  namespace: telecom

spec:
  schedule: "0 2 * * *"

  jobTemplate:

    spec:

      template:

        spec:

          restartPolicy: Never

          containers:

          - name: hello

            image: busybox

            command:
            - /bin/sh
            - -c
            - date; echo "Hello from CronJob"
