apiVersion: v1                      # Kubernetes API version
kind: ConfigMap                     # Resource type

metadata:
  name: {{ .Release.Name }}-config         # ConfigMap name
  namespace: {{ .Release.Namespace }}                # Namespace where it will be created

data:
  APP_NAME: "Telecom API Platform"
  APP_VERSION: "{{ .Release.Namespace }}"
  ENVIRONMENT: "{{ .Values.config.environment }}"
  PORT: "3000"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  COMPANY: "Comviva"
