apiVersion: v1                      # Kubernetes API version
kind: Secret                        # Resource type

metadata:
  name: {{ .Release.Name }}-secret          # Secret name
  namespace: {{ .Release.Namespace }}                # Namespace

type: Opaque                        # Generic Secret

stringData:                         # Plain text values (Kubernetes encodes them)
  DB_USERNAME: "{{ .Values.secret.dbUsername }}"
  DB_PASSWORD: "{{ .Values.secret.dbPassword }}"
  JWT_SECRET: "{{ .Values.secret.jwtSecret }}"
