apiVersion: v1                      # Kubernetes API version
kind: ConfigMap                     # Resource type

metadata:
  name: telecom-api-config          # ConfigMap name
  namespace: telecom                # Namespace where it will be created

data:
  APP_NAME: "Telecom API Platform"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "DEV"
  PORT: "3000"
  LOG_LEVEL: "INFO"
  COMPANY: "Comviva"
