apiVersion: v1                      # Kubernetes API version
kind: Secret                        # Resource type

metadata:
  name: telecom-api-secret          # Secret name
  namespace: telecom                # Namespace

type: Opaque                        # Generic Secret

stringData:                         # Plain text values (Kubernetes encodes them)
  DB_USERNAME: telecom_user
  DB_PASSWORD: telecom@123
  JWT_SECRET: mySuperSecretKey
